# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  steps:

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.6"

  - task: DockerCompose@0
    inputs:
      containerregistrytype: "Azure Container Registry"
      azureSubscription: "Pay-As-You-Go (7a3cd95f-2d6e-4cb6-94ae-52379e216b9a)"
      dockerComposeFile: "**/docker-compose.yml"
      action: "Run a Docker Compose command"
      dockerComposeCommand: "up -d --build"

  # - script: ls $(Pipeline.Workspace)/
  # - script: ls $(Pipeline.Workspace)/a/
  # - script: ls $(Pipeline.Workspace)/s/

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'API Tests'

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: "$(Build.ArtifactStagingDirectory)/test-results.xml"
  #     ArtifactName: "test-result"
  #     # ArtifactType: 'Pipeline'
  #     publishLocation:
  #       "Pipeline"

        #     - task: PublishPipelineArtifact@1
        # inputs:
        #   artifactName: $(app_pipeline_artifact_name)
        #   artifactType: pipeline
